### ISSUE TITLE
i had a question about topguw2

### ISSUE THREAD

**Issue by stackprogramer** [bastienjalbert/topguw2#6]
hi,in topguw 1 or 2 you use rainbow table for cracking gsm.........
and topguw can be used for cracking gsm signal voice  with good quality?
thank you for reply...

**Comment by bastienjalbert** [comment]
Hello RB,

Topguw does'nt use rainbow table actually, the tool porpose is to get
keystream (Topguw 1 works on some environment, Topguw 2 should have a
better compatibility because its using gr-gsm, but I stopped development).

With keystream + rainbow table + Kraken, now you can crack the GSM (final
step, easier step, just passing arguments to Kraken which is connected to
rainbow table).

Cordially,

BE

2016-11-13 15:42 GMT+01:00 R.B notifications@github.com:
